image: gcc

build:
    stage: build
    before_script:
        - apt-get update
        - apt-get install -y git cmake g++ gcovr
    script:
        - mkdir build ; cd build
        - cmake ..
        - make -j
