//
// Created by barte on 11.05.2023.
//

#ifndef SHEEPSKIN_INSTRUMENTDECISIONEVALUATION_H
#define SHEEPSKIN_INSTRUMENTDECISIONEVALUATION_H


class InstrumentDecisionEvaluation {

};


#endif //SHEEPSKIN_INSTRUMENTDECISIONEVALUATION_H
